version: "3.8"

services:
  mongo:
    container_name: mongodb_container
    image: mongo
    restart: always
#    environment:
      #      MONGO_INITDB_ROOT_USERNAME: admin
      #      MONGO_INITDB_ROOT_PASSWORD: admin-password
#      MONGO_INITDB_DATABASE: qrcode
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:



