server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
spring:
  devtools:
   restart:
     enabled: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecom
      auto-index-creation: on
  main:
    web-application-type: servlet

springdoc:
  api-docs:
    path: /api-docs


management:
  endpoints:
    web:
      exposure:
        include: error


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
